README.md

I ran into a copypasta build error for SBT, so I thought I'd pass the corrected dependency names as a PR.
Thanks!

Corrected README.md docs for clojure and sbt builds

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java

fix #51 
make SQSEvent.SQSMessage public

make SQSEvent.SQSMessage public

---

README.md
aws-lambda-java-events/README.md
aws-lambda-java-events/pom.xml

Version bump events library to 2.2.4

Version bump events library to 2.2.4

---

README.md
aws-lambda-java-events/README.md
aws-lambda-java-events/pom.xml

Version bump events library to 2.2.5

Version bump events library to 2.2.5

---

README.md
aws-lambda-java-events/README.md
aws-lambda-java-events/pom.xml

Merge pending artifact publish

Version bump event library to 2.2.6

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoEvent.java

Fixed word `Congnito `to `Cognito` java doc in CognitoEvent.java

Fixed Congnito to Cognito java doc in CognitoEvent

---

aws-lambda-java-core/pom.xml
aws-lambda-java-events/pom.xml
aws-lambda-java-log4j/pom.xml
aws-lambda-java-log4j2/pom.xml

Required for staging future releases

Update nexusUrl in all pom.xml

---

README.md
aws-lambda-java-core/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/pom.xml
aws-lambda-java-log4j/pom.xml
aws-lambda-java-log4j2/README.md
aws-lambda-java-log4j2/pom.xml

https://github.com/aws/aws-lambda-java-libs/issues/89
https://github.com/aws/aws-lambda-java-libs/issues/85
- Bumped minor versions to release `pom.xml` schema fixes
- Updated docs to mention the latest available versions of all packages
- Added `maven.compiler.source` and `maven.compiler.target` properties to all POMs

Bump all packages to new patch version, add maven.compiler properties, update docs

---

.github/workflows/maven-pkg-all.yml

This change adds a GitHub Action workflow to ensure that all packages can be built and tests pass for all PRs and pushes to the master branch.

Add action to build all packages in project

---

aws-lambda-java-events/README.md

(aws-lambda-java-events) Update README.md

---

aws-lambda-java-events/RELEASE.CHANGELOG.md

(aws-lambda-java-events) Update RELEASE.CHANGELOG.md

---

aws-lambda-java-events-sdk-transformer/README.md
aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md
aws-lambda-java-events-sdk-transformer/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml

Pre-release of events version `3.1.1` and sdk-transformer version `2.0.2`

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java

Add Kafka Event

---

aws-lambda-java-core/RELEASE.CHANGELOG.md
aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-log4j2/RELEASE.CHANGELOG.md

For consistency and better readability.

minor: Use full month name in RELEASE.CHANGELOG.md files

---

aws-lambda-java-events/README.md

Add new events to list of supported event models in README.md

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ApplicationLoadBalancerRequestEvent.java

#162 
Adds multiValueQueryStringParameters field

Add multiValueQueryStringParameters

---

README.md

Update README.md with latest versions of the events and sdk-transformer libs

---

aws-lambda-java-events-sdk-transformer/README.md
aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md
aws-lambda-java-events-sdk-transformer/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml

Getting events and sdk-transformer libraries ready for a release.

Stage events v3.5.0 and sdk-transformer v2.0.7

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ActiveMQEvent.java

*Description of changes:* Event sent to Lambda functions when it is integrated with Active MQ as a event source
*Testing* Tested locally to ensure that the Lambda runtime is able to deserialize this new class.

Add ActiveMQ event

---

README.md
aws-lambda-java-events-sdk-transformer/README.md
aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md
aws-lambda-java-events-sdk-transformer/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml
aws-lambda-java-serialization/pom.xml

- `aws-lambda-java-events` to `3.7.0`
- `aws-lambda-java-events-sdk-transformer` to `3.0.2`

Stage events v3.7.0 and sdk-transformer v3.0.2

---

aws-lambda-java-runtime-interface-client/README.md

None
Correcting a few small problems with the RIC README.md

Correcting a few small problems with the README.md

---

aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventsArgumentsProvider.java
aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/HandlerParamsArgumentsProvider.java

*Issue #, if available:* #217
*Description of changes:* Sort the listed files in the event/response folders in order to guarantee the same order.

Force file list ordering for tests

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3ObjectLambdaEvent.java

None.
Support for S3 Object Lambda - as described in this blog - https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/

Feat: S3 Object Lambda support

---

.github/workflows/aws-lambda-java-serialization.yml
README.md
aws-lambda-java-events-sdk-transformer/README.md
aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md
aws-lambda-java-events-sdk-transformer/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3ObjectLambdaEvent.java
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.alpine.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazoncorretto.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazonlinux.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.centos.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.debian.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml
aws-lambda-java-serialization/pom.xml
aws-lambda-java-tests/README.md
aws-lambda-java-tests/RELEASE.CHANGELOG.md
aws-lambda-java-tests/pom.xml

- `aws-lambda-java-events` to `3.8.0`
- `aws-lambda-java-events-sdk-transformer` to `3.0.3`
- `aws-lambda-java-tests` to `1.0.1`

Stage events 3.8.0, sdk transformer 3.0.3, tests 1.0.1

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisEvent.java

https://github.com/aws/aws-lambda-java-libs/issues/244
Fixed toString method.

Issue 244: Fixed toString

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/AppSyncLambdaAuthorizerEvent.java
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/AppSyncLambdaAuthorizerResponse.java

*Issue #, if available:* N/A
*Description of changes:* These changes include the new events to reflect the inputs and outputs of the new AppSync Lambda authorizers feature.

Added new AppSync Lambda authorizer input and output shapes.

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java
aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java
aws-lambda-java-tests/src/test/resources/kafka_event.json

*Description of changes:* This change add headers in KafkaEventRecord 

Add headers in KafkaEventRecord

---

aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/Dockerfile.agent
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.alpine.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazoncorretto.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazonlinux.1.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazonlinux.2.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.centos.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.debian.yml
aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml

fixed docker agent issue, using java 17 instead of java 8

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoUserPoolVerifyAuthChallengeResponseEvent.java
aws-lambda-java-events/src/test/resources/event_models/cognito_user_pool_verify_auth_challenge_response_event.json

https://github.com/aws/aws-lambda-java-libs/issues/355
Changed the challengeAnswer attribute from Map<String, String> to String.

Correct the type for challengeAnswer attribute.

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyRequestEvent.java
aws-lambda-java-events/src/test/resources/event_models/api_gateway_proxy_request_event.json

https://github.com/aws/aws-lambda-java-libs/issues/359
Adding missing attributes to APIGatewayProxyRequestEvent

Adding missing attributes to APIGatewayProxyRequestEvent

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ActiveMQEvent.java
aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java
aws-lambda-java-tests/src/test/resources/mq_event.json

Custom Properties Set by the customer are not being propagated to target function, as we don't have a properties field in here.
Added properties field and also a unit test to see if we are getting right fields.

Integrating Custom Properties to ActiveMQEvent

---

aws-lambda-java-events/README.md
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IoTCustomAuthorizerEvent.java
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IoTCustomAuthorizerResponse.java
aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/LambdaEventSerializersTest.java
aws-lambda-java-events/src/test/resources/event_models/iot_custom_authorizer_event.json
aws-lambda-java-events/src/test/resources/event_models/iot_custom_authorizer_response.json

Adding IoT Custom Authorizer Event and Response to events library

Add IoTCustomAuthorizerEvent and Response

---

.github/workflows/aws-lambda-java-core.yml
.github/workflows/aws-lambda-java-events-sdk-transformer.yml
.github/workflows/aws-lambda-java-events.yml
.github/workflows/aws-lambda-java-log4j2.yml
.github/workflows/aws-lambda-java-runtime-interface-client.yml
.github/workflows/aws-lambda-java-serialization.yml
.github/workflows/aws-lambda-java-tests.yml
.github/workflows/samples.yml

Description of changes:
Rename branch from `master` to `main` at workflows.
https://github.com/aws/aws-lambda-java-libs/issues/387

Update branch to main at workflows

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ActiveMQEvent.java
aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java
aws-lambda-java-tests/src/test/resources/mq_event.json

Lambda Event Source Mapping for ActiveMQ now supports custom properties being sent to customer Lambda functions, adding this so customers using the library have support. Same change as https://github.com/aws/aws-lambda-java-libs/pull/375, just to main branch for earlier release.

Integrates custom properties into ActiveMQ event

---

aws-lambda-java-runtime-interface-client/README.md
aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md
aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ClasspathLoader.java
aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml

Ignore module-info class when preparing CDS archive

ignore module-info class

---

README.md
aws-lambda-java-runtime-interface-client/README.md
aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md
aws-lambda-java-runtime-interface-client/pom.xml
aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml

Bump ric version to 2.3.2

---

README.md
aws-lambda-java-events-sdk-transformer/README.md
aws-lambda-java-events-sdk-transformer/pom.xml
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml
aws-lambda-java-log4j2/pom.xml
aws-lambda-java-tests/pom.xml
samples/kinesis-firehose-event-handler/pom.xml

Bump events version to 3.11.2

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolVerifyAuthChallengeResponseEvent.java

*Issue #, if available:* https://github.com/aws/aws-lambda-java-libs/issues/355
*Description of changes:* Port PR https://github.com/aws/aws-lambda-java-libs/pull/356 to events v3 branch

Correct the type for challengeAnswer attribute. (#356)

---

aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/LambdaLogger.java
aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/logging/LogFormat.java
aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/logging/LogLevel.java

Extending logger interface with level-aware logging backend functions.
---

[alc] Interface changes in the core package (#35)

---

README.md
aws-lambda-java-runtime-interface-client/README.md
aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md
aws-lambda-java-runtime-interface-client/pom.xml
aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml

Stage release 2.4.0. This release brings logging improvements

Stage release 2.4.0

---

README.md
aws-lambda-java-events/README.md
aws-lambda-java-events/RELEASE.CHANGELOG.md
aws-lambda-java-events/pom.xml
aws-lambda-java-tests/pom.xml
samples/kinesis-firehose-event-handler/pom.xml

`3.11.3`:
- Update challengeAnswer field format in CognitoUserPoolEvent 

Stage events 3.11.3

---

aws-lambda-java-runtime-interface-client/README.md
aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md
aws-lambda-java-runtime-interface-client/pom.xml
aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml

Stage release 2.4.1. This release contains a null-pointer bugfix.

Stage release 2.4.1

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/AppSyncLambdaAuthorizerEvent.java

Add requestHeaders field for Appsync lambda authorizer event

---

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPreTokenGenerationEventV2.java
aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventLoader.java
aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java
aws-lambda-java-tests/src/test/resources/cognito_user_pool_pre_token_generation_event_v2.json

https://github.com/aws/aws-lambda-java-libs/issues/464
A new Object to represent the V2 version of the Cognito pre token generation event.
Both (new event)

Adds the V2 version of the pre token generation event.

---

aws-lambda-java-events/README.md
aws-lambda-java-events/pom.xml
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudWatchCompositeAlarmEvent.java
aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudWatchMetricAlarmEvent.java
aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventLoader.java
aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java
aws-lambda-java-tests/src/test/resources/cloudwatch_composite_alarm.json
aws-lambda-java-tests/src/test/resources/cloudwatch_metric_alarm.json

https://github.com/aws/aws-lambda-java-libs/issues/484
Old PR https://github.com/aws/aws-lambda-java-libs/pull/492

Object representations of the CloudWatch alarms

---

README.md

Add clickable Maven badges to README.md

misc: add Maven badges to README

---

.github/workflows/runtime-interface-client_pr.yml
aws-lambda-java-runtime-interface-client/pom.xml

Enable codecov
Example:   https://app.codecov.io/gh/aws/aws-lambda-java-libs/blob/maxday%2Fcodecov/aws-lambda-java-runtime-interface-client%2Fsrc%2Fmain%2Fjava%2Fcom%2Famazonaws%2Fservices%2Flambda%2Fruntime%2Fapi%2Fclient%2Futil%2FEnvReader.java

feat: enable codecov

---

aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/converters/LambdaErrorConverterTest.java

test: add converters tests

---

experimental/aws-lambda-java-profiler/RELEASE.CHANGELOG.md

feat: add changelog for profiler

---

experimental/aws-lambda-java-profiler/extension/src/main/java/com/amazonaws/services/lambda/extension/ExtensionMain.java

Fixes error message for file upload on shutdown

fixed file upload error message

---

aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/Context.java

Add getTenantId() method to core Context interface for better visibility
Both

Add tenant id to Context interface
