aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java
The SQSEvent.SQSMessage class was recently made public but we need to make default constructor public as well
=> Make SQSEvent.SQSMessage default ctor public

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java
*Issue #60*
*Description of changes:* Support for multi-value headers and query string parameters in the Input of a Lambda Function for Proxy Integration. Output remains without change.
=> Support for Multi-Value Headers and Query String Parameters

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3Event.java
Issue #, if available: No issue opened.
Description of changes: Adding a default constructor to the S3Event. The reason for doing this is that it already has another constructor (which gets a list of records), so when working with Jackson we might encounter some issues when trying to deserialize data into this type.
The reason for adding the empty constructor is similar to the one explained here: https://docs.aws.amazon.com/lambda/latest/dg/java-handler-io-type-pojo.html under "note". Also, every other event class has a default constructor.
=> Adding default constructor for S3Event for easier deserialization

.gitignore, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ConfigEvent.java
*Issue #65*
Fixed a typo in method's naming, also did a search and fixed the same in a couple of comments.
**Warning:** as existing API methods are renamed, it's a breaking change.
=> GH-65 Fix "Paramters" typo

aws-lambda-java-log4j2/README.md
When using the config from the readme you get these errors:
```
Error processing element Lambda ([Appenders: null]): CLASS_NOT_FOUND
Unable to locate appender "lambda" for logger config "root"
```
The Lambda documentation site (https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html) does not have the class name in the attribute, and removing the class name makes the errors above go away.
=> Fix the packages directive in the example config

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CodeCommitEvent.java
Issue #78 
Adding customData field, the get and set methods in CodeCommitEvent.Record.
=> Adding customData to CommitEvent.Record

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyResponseEvent.java
*Issue, if available:*  #46
*Description of changes:* Added missing 'isBase64Encoded' field to APIGatewayProxyResponseEvent.java
=> Added missing 'isBase64Encoded' field to APIGatewayProxyResponseEvent

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java
Reopening: https://github.com/aws/aws-lambda-java-libs/pull/39
Adding a map to hold context properties from authorizer. cc: @bmoffatt @oharaandrew314 @miere . This PR was originally submitted by @oharaandrew314 and got closed based on a review comment for using `String` key/values. All other collection fields in this class use `Map<String, String>`. Not sure why we need to worry about other types (non `String`) just for this. We could keep this in the short term until we find a long term solution. Libraries for rest of the programming languages like golang & .Net already support this. Thanks for your support.
=> Adding authorizer field to collect context properties from authorizer

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/pom.xml
Description of changes:
Version bump events library to 2.2.7
=> Version Bump Events Library To 2.2.7

aws-lambda-java-core/pom.xml, aws-lambda-java-events/pom.xml, aws-lambda-java-log4j/pom.xml, aws-lambda-java-log4j2/pom.xml
Without these declarations, the XML file cannot be validated correctly.
See examples:
* <https://maven.apache.org/pom.html#Quick_Overview>
* <https://github.com/aws/aws-sdk-java-v2/blob/master/aws-sdk-java/pom.xml>
The tool I'm using actually tries to validate these before using them
(<https://tiny.amazon.com/ibdzmlln/paste> -- Amazon internal link), so
that's why I ran into issues. I'm assuming most tools don't have the
validation enabled, so this is why others haven't reported this before.
The same issue can be easily replicated by pasting the current POM
files in <https://www.w3schools.com/xml/xml_validator.asp> as well
as just trying to open them with Firefox.
(P.s: Hello there Lambda team! We recently met in your Dublin office!)
By submitting this pull request, I confirm that my …
=> Add missing xml namespace declarations to POM files

README.md, aws-lambda-java-core/RELEASE.CHANGELOG.md, aws-lambda-java-core/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-log4j/RELEASE.CHANGELOG.md, aws-lambda-java-log4j/pom.xml, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
https://github.com/aws/aws-lambda-java-libs/issues/37
- Added per-module changelog files
- Updated readme
=> Add per-module release changelog files, update main readme

aws-lambda-java-log4j2/README.md
*Issue #* : 114
Update Log4j2 README file to include directions when using Gradle and/or the SAM-cli tool
=> #114: Update README.md file for Gradle and SAM tools

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
Previous PR: https://github.com/aws/aws-lambda-java-libs/pull/56
- Updated `log4j-core` and `log4j-api` dependencies from `2.8.2` to `2.13.2` with relevant documentation changes
- Renamed `AWS Lambda Java Log4j 2.8 Libraries` -> `AWS Lambda Java Log4j 2.x Libraries`
- Bumped `aws-lambda-java-log4j2` to `1.2.0`
=> Update log4j-core and log4j-api to 2.13.2

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/DynamodbEventTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbIdentityTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/DynamodbEventTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbIdentityTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbRecordTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformerTest.java
This change adds a new library `aws-lambda-java-events-transformer` to the collection.
Extract from Readme:
Provides helper classes/methods to use alongside `aws-lambda-java-events` in order to transform Lambda input event model objects into SDK-compatible output model objects (eg. DynamodbEvent to a List of records writable back to DynamoDB through the AWS DynamoDB SDK v2).
Add the following Apache Maven dependencies to your `pom.xml` file:
```xml
<dependencies>
<dependency>
<groupId>com.amazonaws</groupId>
<artifactId>aws-lambda-java-events-sdk-transformer</artifactId>
<version>1.0.0</version>
</dependency>
<dependency>
<groupId>com.amazonaws</groupId>
<artifactId>aws-lambda-java-events</artifactId>
<version>2.2.8</version>
</dependency>
</dependencies>
```
To …
=> Add aws-lambda-java-events-sdk-transformer library with DynamodbEvent v2.2.8 support

.github/workflows/maven-pkg-all.yml
With the addition of the `aws-lambda-java-events-sdk-transformer` library, we should also add it to the build Action workflow file. This PR does just that.
=> Add events-sdk-transformer to build workflow

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java
This pull request adds support for operation name in the APIGatewayProxyRequestEvent object. This allows for the name of operation to show up in the backing proxy lambda and allows for the lambda/authorizer to react accordingly.
=> Adding support for OperationName in the APIGatewayProxyRequestEvent

.github/workflows/maven-build-all.yml
This ensures inter-package dependencies are resolved locally by running `mvn install` on modules that are depended on by others locally.
eg:
- `aws-lambda-java-core` is depended on by `aws-lambda-java-log4j` and `aws-lambda-java-log4j2` 
- `aws-lambda-java-events` is depended on by `aws-lambda-java-events-sdk-transformer`
=> Update build workflow to install instead of package

.github/workflows/maven-build-all.yml, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
`aws-lambda-java-events` version bump to `2.2.9` in order to cut a release containing changes from https://github.com/aws/aws-lambda-java-libs/pull/126
=> Bump events lib version to 2.2.9

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/DynamodbEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3Event.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/AttributeValue.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/Identity.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/OperationType.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/Record.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/StreamRecord.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/dynamodb/StreamViewType.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/kinesis/EncryptionType.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/kinesis/Record.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/s3/S3EventNotification.java, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/HttpUtils.java, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/models/s3/S3EventNotificationTest.java
- https://github.com/aws/aws-lambda-java-libs/issues/74
- https://github.com/aws/aws-lambda-java-libs/issues/64
- Removed SDK dependencies from events library
- Copied and adapted relevant S3, Kinesis and DynamoDB model classes
- Bumped to 3.0.0
- Updated relevant docs
=> Remove SDK dependencies from events library

aws-lambda-java-events/README.md, aws-lambda-java-events/pom.xml, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ApplicationLoadBalancerRequestEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ApplicationLoadBalancerResponseEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/82
https://github.com/aws/aws-lambda-java-libs/issues/90
Added support for the ALB request and response events.
=> Application load balancer

aws-lambda-java-events/pom.xml, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPResponse.java
* aws docs reference: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
* equivalent types in other runtimes
* [aws-lambda-dotnet](https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.APIGatewayEvents/APIGatewayHttpApiV2ProxyRequest.cs)
* [aws-lambda-go](https://github.com/aws/aws-lambda-go/blob/master/events/apigw.go#L45-L105)
This change also introduces a build-time dependency on lombok for code-generation.
=> Add APIGateway event for http payload version 2.0

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbIdentityTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbIdentityTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformerTest.java
- Update `aws-lambda-java-events` to version `3.0.0` in SDK Transformer lib dependencies
- Bump DynamoDB SDK to version `2.13.18`
- Bump `aws-lambda-java-events-sdk-transformer` to version `2.0.0`
=> Update SDK Transformer for events v3.0.0

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
*Purpose*
Pre-release of:
- `aws-lambda-java-events` version `3.1.0`
- `aws-lambda-java-events-sdk-transformer` version `2.0.0`
=> Bump events library to 3.1.0

aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbStreamRecordTransformerTest.java
Insert event does not have oldImage. Remove event does not have newImage. At this moment library just throws nullPointerException
=> fix npe when mapping insert / delete events.

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml
Pre-release of `aws-lambda-java-events-sdk-transformer` version `2.0.1`
=> Bump sdk transformer lib to version 2.0.1

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
- Bumping `aws-lambda-java-events` to version `3.2.0`
- Bumping `aws-lambda-java-events-sdk-transformer` to version `2.0.3`
=> Stage events v3.2.0 and sdk-transformer v2.0.3 releases

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ConnectEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/106
Initial event to represent integration with Amazon Connect.
=> initial Amazon Connect event

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudFormationCustomResourceEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/137
Initial event and response to CloudFormation custom resources. 
I couldn't find docs for the json object OldResourceProperties. It looks to be a Map<String, String> in the go events.
=> Initial CloudFormation event and response

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/LambdaDestinationEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/104
Event to represent the Lambda destination event.
Maybe this should be called something else. I'm open to suggestions.
=> initial Lambda destination event

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
- `aws-lambda-java-events` to `3.3.0` 
- `aws-lambda-java-events-sdk-transformer` to `2.0.4`
=> Bump events to 3.3.0 and SDK transformer to 2.0.4

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
**Description of changes:**
- `aws-lambda-java-events` to `3.3.1`
- `aws-lambda-java-events-sdk-transformer` to `2.0.5`
=> Stage events 3.3.1 and sdk-transformer 2.0.5

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java
On Sept 9th,[ API Gateway launched support](https://aws.amazon.com/about-aws/whats-new/2020/09/api-gateway-http-apis-now-supports-lambda-and-iam-authorization-options/) for customers to secure Amazon API Gateway HTTP APIs using two new authorization options: Lambda authorizers and IAM authorizers. These new options enable customers to make flexible authorization decisions by providing an AWS Lambda function, or leveraging AWS IAM policies to control access to their APIs without writing any code. 
Updating API Gateway v2 event to support new context variables.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Update apigatewayv2 request context

aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/dynamodb/DynamodbRecordTransformerTest.java
#168
Fixes a potential NPE when `userIdentity` is null
=> Fix NPE when UserIdentity is null

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
**Description of changes:**
- `aws-lambda-java-events` to `3.4.0`
- `aws-lambda-java-events-sdk-transformer` to `2.0.6`
=> Stage events v3.4.0 and sdk-transformer 2.0.6

aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
**Description of changes:**
- `aws-lambda-java-events` to `3.6.0`
- `aws-lambda-java-events-sdk-transformer` to `2.0.8`
Chore:
- Update `lombok` to `1.18.16`
- Update `junit-jupiter-engine` to `5.7.0`
=> Stage events 3.6.0 and sdk-transformer 2.0.8

.github/workflows/maven-build-all.yml, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.glibc, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/CustomerClassLoaderTest.java, aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/codebuild_build.sh, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.centos.yml
- Included RIC `pr` target in GitHub action and removed the building commands that were already there since the `pr` target would also build them and would generate conflicts
- Removed unnecessary -it option from codebuild_build.sh because it was causing tty error when running the GitHub action
- Refactored a test that uses a special character to expect failure if the encoding is not set to UTF
- Updated to CentOS:7
- Removed CentOS:6 from the OS compatibility test since it reached EOL
=> Include RIC pr target in GitHub action

aws-lambda-java-runtime-interface-client/Makefile, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.glibc, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.musl, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/CustomerClassLoaderTest.java
This PR:
- Changes the RIC's build process to use gcc from `yum` as opposed to building it from source (as it's now a modern supported version after updating to CentOS 7 done [here](https://github.com/aws/aws-lambda-java-libs/pull/193))
- Removes unnecessary `user.dir` overrides in `CustomerClassLoaderTest`
- Adds glibc OS test in test-smoke (now also testing `amazoncorretto` version `11` - previously we were only testing Alpine with musl)
=> Stop building gcc from source

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/DynamodbEventTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbIdentityTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/DynamodbEventTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbIdentityTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/DynamodbEventTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbIdentityTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbRecordTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbStreamRecordTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/DynamodbEventTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbIdentityTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbRecordTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbStreamRecordTransformerTest.java
*Issue #, if available:* https://github.com/aws/aws-lambda-java-libs/issues/182
- Added SDK v1 transformers (under `transformers.v1` package)
- Moved v2 transformers to `transformers.v2` package
- Bumped transformer lib to `3.0.0`
As the scope of these two SDK dependencies is `provided`, users have full control over which to include and use without having to include the other version. I've also opted to separate into different packages to keep a cleaner separation between v1 and v2 models and test cases.
=> Add SDK v1 transformers

.github/workflows/aws-lambda-java-core.yml, .github/workflows/aws-lambda-java-events-sdk-transformer.yml, .github/workflows/aws-lambda-java-events.yml, .github/workflows/aws-lambda-java-log4j2.yml, .github/workflows/aws-lambda-java-runtime-interface-client.yml, .github/workflows/aws-lambda-java-serialization.yml
- GitHub actions workflow currently builds all packages on push and pull request no matter of the package changed
- Separated the GitHub actions workflows to run based on the package changed. It builds the package changed and the packages that depend on that package. There could be some duplication builds if multiple packages are changed in a single pull request, but for most cases it should not be a problem since before including the RIC, building all the other packages took around 1 minute.
=> Separate GitHub actions workflows

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformer.java
https://github.com/aws/aws-lambda-java-libs/issues/198
- Changed scope of `Map<String, AttributeValue> toAttributeValueMapV1(Map<String, AttributeValue>)` to public
- Changed scope of `Map<String, AttributeValue> toAttributeValueMapV2(Map<String, AttributeValue>)` to public
- Bumped sdk transformer to version `3.0.1`
=> Increase scope of toAttributeValueMapV1 and V2, bump transformer to 3.0.1

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/DynamodbTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/StreamsEventResponse.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/TimeWindowEventResponse.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/TimeWindow.java
Added new events `DynamodbTimeWindowEvent` and `KinesisTimeWindowEvent` for supporting stream analytics.
Added a couple of event response classes. `StreamsEventResponse` will be used to report batch item failures for Kinesis and Dynamodb events. `TimeWindowEventResponse` will be used for returning the stream analytics state as well as reporting batch item failures for `KinesisTimeWindowEvent` and `DynamodbTimeWindowEvent`. 
=> New events structures for StreamAnalytics and CustomCheckpointing

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/DynamodbTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KinesisTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/StreamsEventResponse.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/TimeWindowEventResponse.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/models/TimeWindow.java
Added documentation to the new classes introduced for stream analytics and custom checkpointing. The comments should make it easier to distinguish between regular Kinesis and DDB stream processing vs time window based stream processing.
=> Added documentation for stream analytics and custom checkpointing event structures

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/KafkaEvent.java, aws-lambda-java-tests/pom.xml, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java, aws-lambda-java-tests/src/test/resources/kafka_event.json
Add bootstrapServers field to KafkaEvent POJO
=> Add bootstrap servers to Kafka Event

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java
* Added requestId field as it's provided by http gateway V2 (see json below).
Tested on apigw in us-west-2:
```java
public class TestHandler implements RequestHandler<APIGatewayV2HTTPEvent, String> {
@Override
public String handleRequest(APIGatewayV2HTTPEvent apiGatewayV2HTTPEvent, Context context) {
System.out.println(apiGatewayV2HTTPEvent.getRequestContext().getRequestId());
return null;
}
}
```
Original request from apigw:
```json
{
"version": "2.0",
"routeKey": "ANY /printer",
"rawPath": "/printer",
"rawQueryString": "",
"headers": {
"accept": "*/*",
"content-length": "0",
"host": "abcdef.execute-api.us-west-2.amazonaws.com",
"user-agent": "curl/7.71.1",
"x-amzn-trace-id": "Root=1-60583e5a-1f74381240de6ded5a65dbd0",
"x-forwarded-for": "127.0.0.1", …
```
=> ApiGwV2HttpEvent: added requestId

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/AWSLambda.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/LambdaEnvironment.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ReservedRuntimeEnvironmentVariables.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/util/EnvWriter.java
This PR  defines the [AWS Lambda Reserved Environment Variables](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime) in a single place.
=> reserved environment variables constants

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IamPolicyResponseV1.java, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/IamPolicyResponseV1Test.java, aws-lambda-java-events/src/test/resources/iamPolicyV1Responses/allow-with-condition.json, aws-lambda-java-events/src/test/resources/iamPolicyV1Responses/allow.json, aws-lambda-java-events/src/test/resources/iamPolicyV1Responses/deny.json
These are different to HTTP APIs responses as they include a required field for 'usageIdentifierKey'.
https://github.com/aws/aws-lambda-java-libs/issues/184
Feat: Support for IAM Policy Responses for API Gateway REST APIs.
These are different to HTTP APIs responses as they include a required field for 'usageIdentifierKey'.
=> Feat: Support for IAM Policy Responses for API Gateway REST APIs.

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2WebSocketEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/239
Added default IntelliJ equals, hashCode and toString methods.
=> Issue 239: Added default IntelliJ equals, hashCode and toString methods.

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/221
Changed the attribute for body to lowercase.
@carlzogh I don't think this breaks anything for existing customers. What do you think?
=> Issue 221: Changed body to lowercase.

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/246
I've added the principalOrgId to the RequestIdentity object.
=> Issue 246: Added the principalOrgId.

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml, aws-lambda-java-serialization/pom.xml, aws-lambda-java-tests/README.md, aws-lambda-java-tests/RELEASE.CHANGELOG.md, aws-lambda-java-tests/pom.xml
Staging releases:
- `aws-lambda-java-events` version `3.9.0`
- `aws-lambda-java-events-sdk-transformer` version `3.0.4`
- `aws-lambda-java-runtime-interface-client` version `1.1.0`
- `aws-lambda-java-tests` version `1.0.2`
=> Stage events 3.9.0, sdk-transformer 3.0.4, RIC 1.1.0, and tests 1.0.2

aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbStreamRecordTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbRecordTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbStreamRecordTransformerTest.java
#168 same issue as this, which was fixed for SDK v2 in #169 
Fixes a potential NPE when `userIdentity` is null and added a null check to the OldImage and NewImage for dynamo stream records.
=> Fix NPE when user identity is null for SDK v1

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml
Stage `aws-lambda-java-events-sdk-transformer` version `3.0.6`
=> Stage sdk-transformer 3.0.6

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSBatchResponse.java
Adds a new response type to return the list of failed SQS message-ids
=> Adds new response type for SQSaaES Partial Batch Feature

.github/workflows/samples.yml, README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-serialization/pom.xml, aws-lambda-java-tests/README.md, aws-lambda-java-tests/RELEASE.CHANGELOG.md, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
Staging releases:
- `aws-lambda-java-events` version `3.11.0`
- `aws-lambda-java-events-sdk-transformer` version `3.0.7`
- `aws-lambda-java-tests` version `1.1.1`
=> Stage events 3.11.0, sdk-transformer 3.0.7, and tests 1.1.1

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
- Update `log4j-core` and `log4j-api` dependencies to `2.15.0`
- Stage update to `aws-lambda-java-log4j2` version `1.3.0`
=> Update `log4j-core` and `log4j-api` dependencies to `2.15.0`

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
It was found that the fix to address CVE-2021-44228 in Apache Log4j 2.15.0 was incomplete in certain non-default configurations.
The 2.16.0 fixes the CVE-2021-45046 problem.
=> Update log4j-core and log4j-api dependencies to 2.16.0

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
- Update log4j-core and log4j-api dependencies to 2.17.0
- Stage update to aws-lambda-java-log4j2 version 1.5.0
=> Update log4j-core and log4j-api dependencies to 2.17.0

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml
- Update log4j-core and log4j-api dependencies to 2.17.1
- Stage update to aws-lambda-java-log4j2 version 1.5.1
[CVE-2021-44832](https://logging.apache.org/log4j/2.x/security.html#:~:text=CVE-2021-44832)
=> Update log4j-core and log4j-api dependencies to 2.17.1

aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformerTest.java
*Issue #, if available:* https://github.com/aws/aws-lambda-java-libs/issues/224
*Description of changes:* 
This change will make DynamodbAttributeValueTransformer v1 and v2 return empty list instead of null for empty list input.
Transforming empty list to `null` will break functionality for DynamoDB Enhanced library  and make it throw runtime exceptions like:
```
java.lang.IllegalStateException: Unable to convert attribute value: AttributeValue()
```
Also updated corresponding unit test cases.
=> DynamodbAttributeValueTransformer v1 and v2 return empty list instead of null for empty list attribute

README.md, aws-lambda-java-events-sdk-transformer/README.md, aws-lambda-java-events-sdk-transformer/RELEASE.CHANGELOG.md, aws-lambda-java-events-sdk-transformer/pom.xml
Staging release:
- `aws-lambda-java-events-sdk-transformer` version `3.1.0`
=> Bump events-sdk-transformer to 3.1.0

aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformerTest.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbAttributeValueTransformerTest.java
Following-up on https://github.com/aws/aws-lambda-java-libs/pull/309 with added assertions to ensure that returning an immutable `Collections.emptyList()` maintains a consistent behavior when using the transformer library.
The assertion ensures that the returned `List` type is consistent with the object initialized by `AttributeValue` for each SDK version (v1 uses a mutable `ArrayList` whereas v2 uses an immutable `UnmodifiableRandomAccessList`)
=> Assert on AttributeValue List type to ensure consistency when empty and non-empty

aws-lambda-java-serialization/pom.xml, aws-lambda-java-serialization/src/test/java/com/amazonaws/services/lambda/runtime/serialization/events/LambdaEventSerializersTest.java
Make testing more Human-Readable
=> Use JUnit 5 Parameterized Test

.github/workflows/aws-lambda-java-runtime-interface-client.yml, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/NativeClient.java, aws-lambda-java-runtime-interface-client/src/main/jni/build-jni-lib.sh, aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/Dockerfile.agent, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.alpine.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazoncorretto.yml
related to: https://github.com/aws/aws-lambda-java-libs/issues/316
the multi-platform part of the build was silently producing x86_64 artifacts on the VM used to publish to maven, this happens because `docker` on that environment isn't the same as Docker Desktop, so the `--platform` arguments were ignored. https://docs.docker.com/buildx/working-with-buildx/ is required to be configured to correctly produce the runtime-interface-client jar
This change adds just enough validation to `build-jni-lib.sh` to prevent a successful build on an environment without the appropriate build tools. I also updated the GitHub actions to ensure the platform build is regression tested, and the jar is temporarily uploaded for manual inspection if we need it …
=> Ensure at build time that the jni parts of the runtime-interface-client are compiled for the correct architectures

README.md, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml
related to: https://github.com/aws/aws-lambda-java-libs/issues/316
I've staged a release to the re-build I mentioned in: https://github.com/aws/aws-lambda-java-libs/pull/325#issue-1197944312
This PR contains the version bump in the pom.xml and documentation
=> version bump aws-lambda-java-runtime-interface-client 2.1.0 -> 2.1.1

README.md
Seems this has been the case for at least a year https://github.com/boot-clj/boot/issues/768! The URL currently redirects to consumerreports.review
=> remove invalid link from README

aws-lambda-java-runtime-interface-client/Makefile, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.glibc, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.musl, aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/Dockerfile.agent, aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/test_all.sh, aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/test_one.sh, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.alpine.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazoncorretto.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazonlinux.1.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.amazonlinux.2.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.centos.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.debian.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/buildspec.os.ubuntu.yml, aws-lambda-java-runtime-interface-client/test/integration/codebuild/scripts/configure_multi_arch_env.sh, aws-lambda-java-runtime-interface-client/test/integration/docker/Dockerfile.function.alpine, aws-lambda-java-runtime-interface-client/test/integration/docker/Dockerfile.function.amazonlinux, aws-lambda-java-runtime-interface-client/test/integration/docker/Dockerfile.function.centos, aws-lambda-java-runtime-interface-client/test/integration/docker/Dockerfile.function.debian, aws-lambda-java-runtime-interface-client/test/integration/docker/Dockerfile.function.ubuntu
**Enable multi-arch testing**
Currently compatibility tests are failing when trying to build multi-arch JNI libs:
```
Build JNI libraries:
[exec] Compiling the native library for target glibc on architecture x86_64 using Docker platform linux/amd64
[exec] The command '/bin/sh -c rpm --import https://yum.corretto.aws/corretto.key &&     curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo' returned a non-zero code: 1
[exec] tar: This does not look like a tar archive
[exec] tar: Skipping to next header
[exec] tar: src/aws-lambda-runtime-interface-client.so: Not found in archive
[exec] tar: Exiting with failure status due to previous errors
```
* set up a multi-arch build environment prior to building the Runtime …
=> Fix os compatibility tests by enabling multi-platform build and testing

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ClasspathLoader.java
* use correct package name prefix of `NativeClient` class ([see](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/NativeClient.java)): 
`lambdainternal.runtimeapi` -> `com.amazonaws.services.lambda.runtime.api.client.runtimeapi`
* use inclusive language.
=> Use correct package name prefix of 'NativeClient' class

.github/workflows/aws-lambda-java-events.yml, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/EventBridgeEvent.java, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/LambdaEventSerializersTest.java, aws-lambda-java-events/src/test/resources/event_models/eventbridge_event.json
https://github.com/aws/aws-lambda-java-libs/issues/109
Adding EventBridgeEvent
=> Adding EventBridgeEvent

aws-lambda-java-events/pom.xml, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/LambdaEventSerializersTest.java
None 
During debugging of https://github.com/aws/aws-lambda-java-libs/pull/321#issuecomment-1140231679 it was made much easier by the descriptive error messages given by JSONAssert.
=> Adding JSONAssert to ease debugging of event serialisation.

.github/workflows/aws-lambda-java-tests.yml, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SESEvent.java, aws-lambda-java-tests/pom.xml, aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventLoader.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/HandlerParamsTest.java, aws-lambda-java-tests/src/test/resources/cloudwatch_event.json, aws-lambda-java-tests/src/test/resources/ses_event.json
*Description of changes:* 
- Adding SES Event
- Updating test library for events v4 and serialization v2
=> Events v4 serialization v2

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudFormationCustomResourceEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudFrontEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudWatchLogsEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CodeCommitEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ConfigEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ConnectEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IamPolicyResponse.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/IoTButtonEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/LambdaDestinationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/LexEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SNSEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ScheduledEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyRequestEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyResponseEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoUserPoolEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoUserPoolPostAuthenticationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoUserPoolPostConfirmationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/cognito/CognitoUserPoolPreAuthenticationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/dynamodb/DynamodbEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/dynamodb/DynamodbTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/kinesis/KinesisEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/kinesis/KinesisFirehoseEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/kinesis/KinesisTimeWindowEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/s3/S3Event.java
=> Remove Cloneable interface

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/CustomerClassLoader.java
Use a filename filter to only return found jar files. Sorting of the array will only then run on the jar files and not on all files.
=> Optimize jar discovery

aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/Client.java, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/ClientContext.java, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/CognitoIdentity.java, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/LambdaLogger.java, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestHandler.java, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/RequestStreamHandler.java
Based on the definition of an Interface (https://docs.oracle.com/javase/tutorial/java/IandI/interfaceDef.html), the `public` modifier can be omitted.
@bmoffatt 
=> removed unnecessary usage of `public` on interface methods

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CodePipelineEvent.java, aws-lambda-java-events/src/test/java/com/amazonaws/services/lambda/runtime/events/LambdaEventSerializersTest.java, aws-lambda-java-events/src/test/resources/event_models/code_pipeline_event.json, aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventLoader.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java, aws-lambda-java-tests/src/test/resources/codepipeline_event.json
https://github.com/aws/aws-lambda-java-libs/issues/16
Adding the CodePipelineEvent
=> Adding the CodePipelineEvent

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyRequestEvent.java, aws-lambda-java-events/src/test/resources/event_models/api_gateway_proxy_request_event.json
https://github.com/aws/aws-lambda-java-libs/issues/365
Added the client cert attributes
=> Adding the client cert attributes

aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformer.java, aws-lambda-java-events-sdk-transformer/src/test/java/com/amazonaws/services/lambda/runtime/events/transformers/v1/dynamodb/DynamodbAttributeValueTransformerTest.java
None
Old image and new image don't always exist in the DynamoDB stream record. When either of them don't exist, a NullPointerException would be thrown without null checks. The same null checks exist in [com.amazonaws.services.lambda.runtime.events.transformers.v2.dynamodb.DynamodbStreamRecordTransformer](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events-sdk-transformer/src/main/java/com/amazonaws/services/lambda/runtime/events/transformers/v2/dynamodb/DynamodbStreamRecordTransformer.java#L16-L25), but not com.amazonaws.services.lambda.runtime.events.transformers.v1.dynamodb.DynamodbStreamRecordTransformer
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Add null checks to handle null new image and old image in StreamRecord

aws-lambda-java-core/RELEASE.CHANGELOG.md, aws-lambda-java-core/pom.xml, aws-lambda-java-core/src/main/java/com/amazonaws/services/lambda/runtime/CustomPojoSerializer.java
`1.2.2`:
- Added new `CustomPojoSerializer` interface
- Removed unnecessary usage of public on interface methods (aws#172) 
=> 1.2.2 lambda-java-core release

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/AWSLambda.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/FramedTelemetryLogSink.java, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/logging/FramedTelemetryLogSinkTest.java
Socket cannot be re-opened (unlike pipes and regular files). We we have to reflectively construct the `FileDescriptor` with the right number as it does not have a constructor that takes int.
=> Support sockets as transport for framed telemetry

README.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml
Update Jackson dependencies, junit version, owasp plugin version
=> 1.0.1 lambda-java-serialization release

.github/workflows/aws-lambda-java-core.yml, .github/workflows/aws-lambda-java-events-sdk-transformer.yml, .github/workflows/aws-lambda-java-events.yml, .github/workflows/aws-lambda-java-log4j2.yml, .github/workflows/aws-lambda-java-runtime-interface-client.yml, .github/workflows/aws-lambda-java-serialization.yml, .github/workflows/aws-lambda-java-tests.yml, .github/workflows/samples.yml
Description of changes:
This addresses workflow warnings:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update github actions for runtime-interface-client

aws-lambda-java-runtime-interface-client/test/integration/codebuild-local/Dockerfile.agent
Update apache-maven to `3.8.7` in `test/integration/codebuild-local`.
=> Update apache-maven to 3.8.7

aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md, aws-lambda-java-runtime-interface-client/pom.xml
Staging version 2.2.0 of RIC
- Added timestamps to TLV
- Removed legacy `init` method support
- libcurl updated to version 7.86
- Support sockets as transport for framed telemetry
- Updated aws-lambda-java-core to 1.2.2
=> Release aws-lambda-java-runtime-interface-client, version 2.2.0

aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml
**1.0.2 lambda-java-serialization release:**
* Update Gson to `2.10.1`
=> 1.0.2 lambda-java-serialization release

aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml, aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/factories/JacksonFactory.java
**1.1.0 lambda-java-serialization release:**
- Update `jackson-databind` dependency from 2.13.4.1 to 2.14.2
- Register `JavaTimeModule` and `Jdk8Module` modules to `jackson-databind`
=> 1.1.0 lambda-java-serialization release

aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml, aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/modules/DateTimeModule.java, aws-lambda-java-serialization/src/test/java/com/amazonaws/services/lambda/runtime/serialization/events/LambdaEventSerializersTest.java
* Register `JodaModule` to JacksonFactory
`jackson-databind >= v2.12.0` explicitly fails (de)serialization of `org.joda.time.*` types in absence of registered custom (de)serializers. [PR #2776](https://github.com/FasterXML/jackson-databind/issues/2776)
Registering `JodaModule` module is required to (de)serialize `org.joda.time.*` types.
*Test*:
EventsV3 unit tests
=> 1.1.1 lambda-java-serialization release

aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml
Staging new version of the events library - 3.11.1:
It brings security fixes and updates ActiveMQEvent with custom properties.
- Extended ActiveMQEvent with custom properties ([#408](https://github.com/aws/aws-lambda-java-libs/pull/408))
- Updated dependencies([#410](https://github.com/aws/aws-lambda-java-libs/pull/410)):
- `joda-time` from 2.6 to 2.10.8
- `jackson-databind` from 2.13.4.1 to 2.14.2
- `junit-jupiter-engine` from 5.7.0 to 5.9.2
- `json-unit-assertj` from 2.22.0 to 2.36.1
=> Stage aws-lambda-java-events 3.11.1

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/AWSLambda.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ClasspathLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/EventHandlerLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/Failure.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/HandlerInfo.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/LambdaEnvironment.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/PojoSerializerLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ReservedRuntimeEnvironmentVariables.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/TooManyServiceProvidersFoundException.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/UserFault.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/XRayErrorCause.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/api/LambdaClientContext.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/api/LambdaContext.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/FramedTelemetryLogSink.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/StdOutLogSink.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/InvocationRequest.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeClient.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/NativeClient.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/util/LambdaOutputStream.java
- Reformatted sources with idea default formatter.
- Revisited methods visibility in `EventHandlerLoader`
=> Formatting and making some methods private

aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.glibc, aws-lambda-java-runtime-interface-client/src/main/jni/Dockerfile.musl, aws-lambda-java-runtime-interface-client/src/main/jni/deps/curl_001_disable_wakeup.patch
=> Add curl patch

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayProxyRequestEvent.java
There was a similar PR in the past: #93 but at that point the fields were added to the V2 and the WebSockets events and not to the traditional proxy event.
*Description of changes:* 
* extendedRequestId
* requestTime
* requestTimeEpoch
* domainName
* protocol
=> Add missing fields to API Gateway request context

aws-lambda-java-runtime-interface-client/Makefile, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/ric-dev-environment/publish_snapshot.sh, aws-lambda-java-runtime-interface-client/ric-dev-environment/test-platform-specific-jar-snapshot.sh, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/ClasspathLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/EventHandlerLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/InvocationRequest.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeClient.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/NativeClient.java, aws-lambda-java-runtime-interface-client/src/main/jni/build-jni-lib.sh, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/EventHandlerLoaderTest.java, aws-lambda-java-runtime-interface-client/src/test/java/test/lambda/handlers/POJOHanlderImpl.java, aws-lambda-java-runtime-interface-client/src/test/java/test/lambda/handlers/RequestHandlerImpl.java, aws-lambda-java-runtime-interface-client/src/test/java/test/lambda/handlers/RequestStreamHandlerImpl.java
*Description of changes:* Prepare platform specific artifacts. After this change, the following jar files will be prepared as part of the build:
```
-rw-r--r--  1 smirnoal  user   1.1M 17 Jul 13:20 target/aws-lambda-java-runtime-interface-client-2.3.2-linux-aarch_64.jar
-rw-r--r--  1 smirnoal  user   1.1M 17 Jul 13:19 target/aws-lambda-java-runtime-interface-client-2.3.2- linux-x86_64.jar
-rw-r--r--  1 smirnoal  user   839K 17 Jul 13:20 target/aws-lambda-java-runtime-interface-client-2.3.2-linux_musl-aarch_64.jar
-rw-r--r--  1 smirnoal  user   850K 17 Jul 13:19 target/aws-lambda-java-runtime-interface-client-2.3.2-linux_musl-x86_64.jar
-rw-r--r--  1 smirnoal  user   2.2M 17 Jul 13:19 target/aws-lambda-java-runtime-interface-client-2.3.2.jar
```
Also, a new system property was introduced …
=> Prepare platform specific jar files

README.md, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml
*Description of changes:* Release new version of Runtime interface client - 2.3.3
This release includes building platform/arch specific artefacts and NativeClient optimisations
=> Stage release 2.3.3

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolCreateAuthChallengeEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolCustomMessageEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolDefineAuthChallengeEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolMigrateUserEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPostAuthenticationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPostConfirmationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPreAuthenticationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPreSignUpEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolPreTokenGenerationEvent.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CognitoUserPoolVerifyAuthChallengeResponseEvent.java
https://github.com/aws/aws-lambda-java-libs/issues/433
Add super.toString() to cognito generated classes
=> Add super.toString() to Cognito events

aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml, aws-lambda-java-serialization/verify-relocation.sh
Issue #, if available:
Description of changes:
Currently events v4 are not supporting, because of maven shade plugin relocate whole com.fasterxml.jackson package.
At this pull request I am excluding Jackson annotations interfaces(with minimal change risk). It will enable support Events v4 lib
Target (OCI, Managed Runtime, both):
both
=> Add support for events v4

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ScheduledEvent.java
*Issue #, if available:* Mentioned in [#47](https://github.com/aws/aws-lambda-java-libs/issues/47)
*Description of changes:* Added missing 'version' field to [ScheduledEvent](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ScheduledEvent.java) from CloudWatch based on official documentation [[1]](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events-structure.html) [[2]](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-and-eventbridge.html)
=> Added missing 'version' field to ScheduledEvent from CloudWatch

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/apigateway/APIGatewayProxyRequestEvent.java, aws-lambda-java-events/src/test/resources/event_models/api_gateway_proxy_request_event.json
The "version" field is missing in APIGatewayProxyRequestEvent based on the official [documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format).
=> Added missing 'version' field to APIGatewayProxyRequestEvent

README.md, aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml, aws-lambda-java-serialization/verify-relocation.sh, aws-lambda-java-tests/pom.xml
*Issue #, if available:* https://github.com/aws/aws-lambda-java-libs/issues/448
*Description of changes:*  Stage version 1.1.4:
- Update org.json version to 20231013
- Rollback relocation changes
=> Stage aws-lambda-java-serialization 1.1.4

README.md, aws-lambda-java-log4j2/README.md, aws-lambda-java-log4j2/RELEASE.CHANGELOG.md, aws-lambda-java-log4j2/pom.xml, aws-lambda-java-log4j2/src/main/java/com/amazonaws/services/lambda/runtime/log4j2/LambdaAppender.java, aws-lambda-java-log4j2/src/main/java/com/amazonaws/services/lambda/runtime/log4j2/LambdaJsonFormat.java, aws-lambda-java-log4j2/src/main/java/com/amazonaws/services/lambda/runtime/log4j2/LambdaTextFormat.java, aws-lambda-java-log4j2/src/main/resources/LambdaLayout.json
Log level and log format support in log4j2.
---
=> [alc] Log4j2 support (#37)

aws-lambda-java-events/pom.xml
We should avoid we introduce a particular annotation library into the dependency of users of the library. There are a lot of libraries out there and users may have a different preference. I've changed the scope to provided according to the docs https://github.com/JetBrains/java-annotations#using-the-annotations.
=> change scope for jetbrains annotations to provided

aws-lambda-java-log4j2/README.md
Small changes in the README to make it easier to set up logging properly.
---
=> Updated readme for log4j2 (#46)

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ConnectEvent.java, aws-lambda-java-events/src/test/resources/event_models/connect_event.json
Update ConnectEvent Queue definition. According to Amazon Connect latest doc: https://docs.aws.amazon.com/connect/latest/adminguide/connect-lambda-functions.html#function-contact-flow, Queue is an Object. Current type definition is String, which causes parsing error
```Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
at [Source: (ByteArrayInputStream); line: 1, column: 580] (through reference chain: com.amazonaws.services.lambda.runtime.events.ConnectEvent["Details"]->com.amazonaws.services.lambda.runtime.events.ConnectEvent$Details["ContactData"]->com.amazonaws.services.lambda.runtime.events.ConnectEvent$ContactData["Queue"])```
*Target (OCI, Managed Runtime, both):*Managed Runtime
By …
=> update ConnectEvent queue definition

README.md, aws-lambda-java-serialization/RELEASE.CHANGELOG.md, aws-lambda-java-serialization/pom.xml, aws-lambda-java-tests/pom.xml
*Description of changes:* Stage new version of aws-lambda-java-serialization
*Changelog:* Add support for DynamodbEvent.DynamodbStreamRecord serialization
=> Stage aws-lambda-java-serialization 1.1.5

aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/AWSLambda.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/AbstractLambdaLogger.java, aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml
The change logs the exceptions caught by the runtime with `ERROR` log level, but only in JSON format, because in TEXT mode the `[ERROR] ` prefix would be added to the log message, which may be an unexpected change for customers.
=> Userexception logged as error in json public

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
*Description of changes:* Stage new revision of aws-lambda-java-events 3.11.5
=> Stage aws-lambda-java-events 3.11.5

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
Stage new revision of `aws-lambda-java-events` `3.11.6`
=> Stage aws-lambda-java-events 3.11.6

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
Bump aws-lambda-java-events from `3.11.6` to `3.12.0`
=> bump: aws-lambda-java-events from 3.11.6 to 3.12.0

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeApiClientImpl.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/NativeClient.java, aws-lambda-java-runtime-interface-client/src/main/jni/com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.cpp, aws-lambda-java-runtime-interface-client/src/main/jni/com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.h
To be able to test this JNI code, and the runtime api lifecycle, this is a required change so we could inject a mock http server.
This PR transforms NativeClient.init in a pure function as well as initializeClient.
=> fix: make initializeClient a pure function

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchEventV2.java, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchResponse.java, aws-lambda-java-tests/src/main/java/com/amazonaws/services/lambda/runtime/tests/EventLoader.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/S3BatchEventV2Test.java, aws-lambda-java-tests/src/test/resources/s3_batch_event_v2.json
*Issue  #495*
Add a new S3BatchEventV2 class representing an Event coming from S3 when using invocation schema version 2.
Compared to the other version, it adds the user arguments and changes the bucket ARN to the name.
Unsure yet
=> Add S3BatchEventV2

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
Bump aws-lambda-java-events from `3.12.0` to `3.13.0`
=> bump: aws-lambda-java-events from 3.12.0 to 3.13.0

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/AWSLambda.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/DtoSerializers.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaError.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeApiClient.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeApiClientImpl.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/RapidErrorType.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/converters/LambdaErrorConverter.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/dto/ErrorRequest.java
*Issue #, if available:* integration tests failures 
*Description of changes:* Use "Lambda-Runtime-Function-Error-Type" header to report valid error types to RAPID instead of exception class names.
=> Use Lambda-Runtime-Function-Error-Type for reporting errors in format "Runtime.<Error>"

aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeApiClientImplTest.java
Adding unit tests: going from 13% to 88% for runtimeapi package
=> misc: add unit test for runtime API

README.md, aws-lambda-java-runtime-interface-client/README.md, aws-lambda-java-runtime-interface-client/RELEASE.CHANGELOG.md, aws-lambda-java-runtime-interface-client/pom.xml, aws-lambda-java-runtime-interface-client/test/integration/test-handler/pom.xml
Bump `aws-lambda-java-runtime-interface-client` to `2.6.0`
=> bump: RIC to 2.6.0

aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3BatchEventV2.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/S3BatchEventV2Test.java
Fix the name of the s3Bucket field, which was previously incorrect. Add a test for that specific field.
unknown
=> Fix name of s3Bucket field of Task class in S3BatchEventV2

aws-lambda-java-runtime-interface-client/pom.xml
Add a minimum ratio (current value) for code coverage.
This will raise an error if coverage ratio is not met:
=> feat: add minimum covered ratio rate

README.md, aws-lambda-java-events/README.md, aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/pom.xml, aws-lambda-java-tests/pom.xml, samples/kinesis-firehose-event-handler/pom.xml
*Description of changes:*  Release new version of awa-lambda-java-events library
=> New version of aws-lambda-java-events

aws-lambda-java-events/RELEASE.CHANGELOG.md, aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SecretsManagerRotationEvent.java, aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/mixins/SecretsManagerRotationEventMixin.java, aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java, aws-lambda-java-tests/src/test/resources/secrets_rotation_event.json
*Issue #, if available:* RotationToken was introduced to SecretsManager Rotation Event. 
*Description of changes:* Add RotationToken field to SecretsManager Rotation Event. 
=> Add Rotation Token for SecretsManager Rotation Event

experimental/aws-lambda-java-profiler/update-function.sh
Currently, the script overrides existing env vars. This is dangerous, especially if someone used it by mistake for production lambda.
=> Fix env vars override bug.

.github/workflows/aws-lambda-java-profiler.yml, experimental/aws-lambda-java-profiler/README.md, experimental/aws-lambda-java-profiler/extension/build.gradle
#529
Update the troubleshooting section.
Bump s3 sdk
both
=> fix: Readme and troubleshooting section

.github/workflows/samples.yml
Fix sample builds by installing `aws-lambda-java-serialization` first
both
=> fix: samples

experimental/aws-lambda-java-profiler/extension/src/main/java/com/amazonaws/services/lambda/extension/PreMain.java, experimental/aws-lambda-java-profiler/extension/src/main/java/com/amazonaws/services/lambda/extension/ShutdownHook.java
fixes: https://github.com/aws/aws-lambda-java-libs/issues/536
Respect PROFILER_STOP_COMMAND in Shutdown hook
both
=> fix: use PROFILER_STOP_COMMAND in Shutdown hook

aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/EventHandlerLoader.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/api/LambdaContext.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/JsonLogFormatter.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/logging/StructuredLogMessage.java, aws-lambda-java-runtime-interface-client/src/main/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/dto/InvocationRequest.java, aws-lambda-java-runtime-interface-client/src/main/jni/com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.cpp, aws-lambda-java-runtime-interface-client/src/main/jni/deps/aws-lambda-cpp-0.2.7/include/aws/lambda-runtime/runtime.h, aws-lambda-java-runtime-interface-client/src/main/jni/deps/aws-lambda-cpp-0.2.7/src/runtime.cpp, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/api/LambdaContextTest.java, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/logging/JsonLogFormatterTest.java, aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/runtimeapi/LambdaRuntimeApiClientImplTest.java
- Add tenant id to LambdaContext object and structured log messages 
- Both
=> Add tenant id to lambda context and structured log messages

aws-lambda-java-runtime-interface-client/src/test/java/com/amazonaws/services/lambda/runtime/api/client/PojoSerializerLoaderTest.java
*Issue #, if available:* EventHandlerLoaderTest fails when run after PojoSerializerLoaderTest.
*Description of changes:* EventHandlerLoaderTest fails when run after PojoSerializerLoaderTest. This was caused by not resetting static fields that were modified by the tests inPojoSerializerLoaderTest after the tests are done.
=> Fix EventHandlerLoaderTest failing after PojoSerializerLoaderTest
